flowchart TB
    %% project Module Dependency Flowchart
    module_DevBridge_Electron["DevBridge-Electron\n模块"]
    module_DevBridge_Front["DevBridge-Front\n模块"]
    module_devbridge_server["devbridge.server\n模块"]