flowchart TB
    %% project - DevBridge-Electron Components
    subgraph group_function["function 组件"]
            function_0_d["d\njavascript / d 函数"]
            function_1_g["g\njavascript / g 函数"]
            function_2_ap["ap\njavascript / ap 函数"]
            function_3_up["up\njavascript / up 函数"]
            function_4_A["A\njavascript / A 函数"]
            function_5_T["T\njavascript / T 函数"]
            function_6_ne["ne\njavascript / ne 函数"]
            function_7_Me["Me\njavascript / Me 函数"]
            function_8_De["De\njavascript / De 函数"]
            function_9_oe["oe\njavascript / oe 函数"]
            function_10_re["re\njavascript / re 函数"]
            function_11_se["se\njavascript / se 函数"]
            function_12_Se["Se\njavascript / Se 函数"]
            function_13_et["et\njavascript / et 函数"]
            function_14_ft["ft\njavascript / ft 函数"]
            function_15_Ve["Ve\njavascript / Ve 函数"]
            function_16_D["D\njavascript / D 函数"]
            function_17_pa["pa\njavascript / pa 函数"]
            function_18_cp["cp\njavascript / cp 函数"]
            function_19_R["R\njavascript / R 函数"]
        end